stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start &
    # run Cypress front-end tests
    - npm  cypress run --spec cypress/e2e/frontend --browser chrome --headed
    # run Cypress api tests
    - npm  cypress run --spec cypress/e2e/api --browser chrome --headed
